package fr.ensisa.hassenforder.shopping.client.ui;

import fr.ensisa.hassenforder.shopping.client.model.Item;

/**
 *
 * @author hassenforder
 */
public class CaddyItem extends javax.swing.JPanel {

    private GUIListener listener;
    private Item item;

    /**
     * Creates new form CaddyItem
     */
    public CaddyItem(Item item, GUIListener listener) {
        initComponents();
        this.item = item;
        this.listener = listener;
        updateView ();
    }

    public Item getItem() {
        return item;
    }

    public void updateView () {
        jItemName.setText(item.getName());
        jItemCount.setText(Integer.toString(item.getCount()));
        if (listener != null) listener.onGetHalfPicture (jPicture, item.getProduct().getId());
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jItemName = new javax.swing.JLabel();
        jItemCount = new javax.swing.JLabel();
        jItemInc = new javax.swing.JButton();
        jItemDec = new javax.swing.JButton();
        jPicture = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(261, 25));
        setMinimumSize(new java.awt.Dimension(261, 25));
        setPreferredSize(new java.awt.Dimension(261, 25));

        jItemName.setText("name");

        jItemCount.setText("count");

        jItemInc.setLabel("+");
        jItemInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemIncActionPerformed(evt);
            }
        });

        jItemDec.setLabel("-");
        jItemDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemDecActionPerformed(evt);
            }
        });

        jPicture.setText("jPicture");
        jPicture.setMaximumSize(new java.awt.Dimension(24, 24));
        jPicture.setMinimumSize(new java.awt.Dimension(24, 24));
        jPicture.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jItemCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jItemInc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jItemDec)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jItemInc)
                    .addComponent(jItemDec)
                    .addComponent(jItemCount)
                    .addComponent(jItemName)
                    .addComponent(jPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jItemIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemIncActionPerformed
        if (listener != null) listener.onClickIncrementCaddyItemCount(this);
    }//GEN-LAST:event_jItemIncActionPerformed

    private void jItemDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemDecActionPerformed
        if (listener != null) listener.onClickDecrementCaddyItemCount(this);
    }//GEN-LAST:event_jItemDecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jItemCount;
    private javax.swing.JButton jItemDec;
    private javax.swing.JButton jItemInc;
    private javax.swing.JLabel jItemName;
    private javax.swing.JLabel jPicture;
    // End of variables declaration//GEN-END:variables
}
