package fr.ensisa.hassenforder.shopping.client.ui;

import fr.ensisa.hassenforder.shopping.client.model.Product;

/**
 *
 * @author hassenforder
 */
public class ProductItem extends javax.swing.JPanel {

    private GUIListener listener;
    private Product product;
    
    /**
     * Creates new form CaddyItem
     */
    public ProductItem(Product product, GUIListener listener) {
        initComponents();
        this.product = product;
        this.listener = listener;
        updateView ();
    }

    public Product getProduct() {
        return product;
    }

    public void updateView() {
        jName.setText(product.getName());
        jCategory.setText(product.getCategory());
        if (listener != null) listener.onGetPicture (jPicture, product.getId());
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jName = new javax.swing.JLabel();
        jCategory = new javax.swing.JLabel();
        jProductBuy = new javax.swing.JButton();
        jPicture = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(332, 56));
        setMinimumSize(new java.awt.Dimension(332, 56));
        setPreferredSize(new java.awt.Dimension(332, 56));

        jName.setText("name");

        jCategory.setText("category");

        jProductBuy.setLabel("+");
        jProductBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductBuyActionPerformed(evt);
            }
        });

        jPicture.setText("jLabel1");
        jPicture.setMaximumSize(new java.awt.Dimension(48, 48));
        jPicture.setMinimumSize(new java.awt.Dimension(48, 48));
        jPicture.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProductBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCategory)
                    .addComponent(jProductBuy))
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jProductBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductBuyActionPerformed
        if (listener != null) listener.onClickBuyProduct(this);
    }//GEN-LAST:event_jProductBuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCategory;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jPicture;
    private javax.swing.JButton jProductBuy;
    // End of variables declaration//GEN-END:variables

}
